#PORT
server:
  port: 80

#DB
# p:url=""의 방식이 바뀜 (계층 구조의 방식)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?autoReconnection=true
    username: root
    password: happy
    driver-class-name: com.mysql.cj.jdbc.Driver

#MyBatis
#JPA
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb
# log 파일 처리 => 실행 시 마다 SQL문장 출력 요청
        show_sql: true
        format_sql: true
        use_sql_comments: true

#ThymeLeaf
  thymeleaf: 
    cache: false
    encoding: utf-8
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
  elasticsearch:
    uris: localhost:9200	